language: python
services:
  - postgresql
python:
  - "2.7"
before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
script:
    - pytest --cov=./lessandro
env:
    - DATABASE_URL="dbname='travis_ci_test'"
after_success:
- codecov
